### ISSUE TITLE
请问这个时因为什么问题？

### ISSUE THREAD

**Issue by NUCsimple** [V-I-C-T-O-R/12306#13]
Traceback (most recent call last):
  File "fuckeverything.py", line 8, in <module>
    from spider.get_free_proxy import GetFreeProxy
  File "/home/carvin/gitfile/12306/spider/get_free_proxy.py", line 50
    yield tr.xpath("./td[1]/text()")[0] + ":" + tr.xpath("./td[2]/text()")[0]
SyntaxError: 'return' with argument inside generator

**Comment by V-I-C-T-O-R** [comment]
@NUCsimple 暂时没有遇到这类问题噢
