### ISSUE TITLE
我一直登录不上，是什么原因？sqlite需要安装吗？

### ISSUE THREAD

**Issue by bambi2016** [V-I-C-T-O-R/12306#17]
我报错如下：一直登录不上！
不知道是哪里出了问题。
有效ip代理数量：84
正在登录...
第1次尝试获取验证图片
Traceback (most recent call last):
  File "/Users/wujianhua/python/12306/fuckeverything.py", line 135, in <module>
    main()
  File "/Users/wujianhua/python/12306/fuckeverything.py", line 83, in main
    result, msg = login.login(USER_NAME, USER_PWD, SELECT_AUTO_CHECK_CAPTHCA)
  File "/Users/wujianhua/python/12306/train/login/Login.py", line 76, in login
    result, msg = self._login(userName, userPwd, autoCheck, type=(count % 2))
  File "/Users/wujianhua/python/12306/train/login/Login.py", line 18, in wrapper
    reslut, msg = func(*args, **kw)
  File "/Users/wujianhua/python/12306/train/login/Login.py", line 87, in _login
    return self._loginNormal(userName, userPwd,autoCheck)
  File "/Users/wujianhua/python/12306/train/login/Login.py", line 91, in _loginNormal
    self._uamtk()
  File "/Users/wujianhua/python/12306/train/login/Login.py", line 49, in _uamtk
    jsonRet['result_message'] if 'result_message' in jsonRet else 'no result_message', \
TypeError: argument of type 'NoneType' is not iterable

**Comment by bambi2016** [comment]
有时是能出来验证码，但正确填写验证码后还是登录失败。账号密码确认没问题的。

**Comment by V-I-C-T-O-R** [comment]
最近12306登陆方式有变化，具体问题得具体调试。测试过程中发现在10次登陆过程中，前几次都会失败，而且是12306方的无响应

**Comment by V-I-C-T-O-R** [comment]
@bambi2016 新增了验证方式，测试了几次，基本上10次之内可以通过登录，你试试吧
