### ISSUE TITLE
运行时候报错： 'CXW' is not in list

### ISSUE THREAD

**Issue by chenzhuo2016** [V-I-C-T-O-R/12306#2]
不知道这个CXW是个啥东西 代码里也没搜到 望楼主解答下

**Comment by chenzhuo2016** [comment]
Traceback (most recent call last):
  File "F:/Python Project/12306-master/train/query/Query.py", line 209, in <module>
    Query.outputPretty('2019-02-12', '重庆', '上海')
  File "F:/Python Project/12306-master/train/query/Query.py", line 137, in outputPretty
    for ticket in Query.query(1, base_query_url, trainDate, fromStation, toStation, passengerType):
  File "F:/Python Project/12306-master/train/query/Query.py", line 124, in __decode
    ticket.startStation = code2city(ticket.startStationCode)
  File "F:\Python Project\12306-master\conf\city_code.py", line 5364, in code2city
    return CITY_NAME[CITY_CODE.index(cityCode)]
ValueError: 'CXW' is not in list


贴不鸟图 估计在这儿

**Comment by V-I-C-T-O-R** [comment]
@chenzhuo2016 你更新一下代码(你的运气真好，刚刚重庆西站没有)-_-
