### ISSUE TITLE
验证码识别错误后报错

### ISSUE THREAD

**Issue by github-superadmin** [V-I-C-T-O-R/12306#26]
# 1表示手动,2表示自动识别(调用第三方接口,已失效),3表示使用本工具自己捣鼓的验证码识别方式(配置百度ai/tencent ai账号)
SELECT_AUTO_CHECK_CAPTHCA = 1

正在登录...
第1次尝试获取验证图片
正在获取验证码..
验证码识别错误!
第2次尝试获取验证图片
Traceback (most recent call last):
  File "C:/py12306-master/fuckeverything.py", line 129, in <module>
    main()
  File "C:/py12306-master/fuckeverything.py", line 48, in main
    status,login = do_login()
  File "C:/py12306-master/fuckeverything.py", line 23, in do_login
    result, msg = login.login(USER_NAME, USER_PWD, SELECT_AUTO_CHECK_CAPTHCA)
  File "C:\py12306-master\train\login\Login.py", line 85, in login
    result, msg = self._login(userName, userPwd, autoCheck, type = 0)
  File "C:\py12306-master\train\login\Login.py", line 20, in wrapper
    reslut, msg = func(*args, **kw)
  File "C:\py12306-master\train\login\Login.py", line 96, in _login
    return self._loginNormal(userName, userPwd,autoCheck, type)
  File "C:\py12306-master\train\login\Login.py", line 99, in _loginNormal
    status,msg = self._login_init()
  File "C:\py12306-master\train\login\Login.py", line 185, in _login_init
    text = json.loads(callback)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by github-superadmin** [comment]
设置为手动打码，但是报错。请问作者这个咋解决？

**Comment by V-I-C-T-O-R** [comment]
@github-superadmin 更新下代码，更新deviceId
