### ISSUE TITLE
识别验证码成功 后报错

### ISSUE THREAD

**Issue by adminSxs** [V-I-C-T-O-R/12306#61]
Traceback (most recent call last):
  File "fuckeverything.py", line 147, in <module>
    main()
  File "fuckeverything.py", line 66, in main
    status,login = do_login()
  File "fuckeverything.py", line 24, in do_login
    result, msg = login.login(USER_NAME, USER_PWD, SELECT_AUTO_CHECK_CAPTHCA)
  File "D:\github\12306\train\login\Login.py", line 89, in login
    result, msg = self._login(userName, userPwd, autoCheck, type = 0)
  File "D:\github\12306\train\login\Login.py", line 24, in wrapper
    reslut, msg = func(*args, **kw)
  File "D:\github\12306\train\login\Login.py", line 100, in _login
    return self._loginNormal(userName, userPwd,autoCheck, type)
  File "D:\github\12306\train\login\Login.py", line 110, in _loginNormal
    results, verify = Captcha().verifyCaptchaByHand(type=type)
  File "D:\github\12306\train\login\Capthca.py", line 94, in verifyCaptchaByHand
    return results, self.check(results, type)
  File "D:\github\12306\train\login\Capthca.py", line 30, in check
    return self._captchaCheck(results)
  File "D:\github\12306\train\login\Capthca.py", line 59, in _captchaCheck
    return verify(jsonRet)
  File "D:\github\12306\train\login\Capthca.py", line 57, in verify
    'result_code'] if 'result_code' in response else False
TypeError: argument of type 'NoneType' is not iterable

**Comment by V-I-C-T-O-R** [comment]
更新device url
